### ISSUE TITLE
Sppech Identification

### ISSUE THREAD

**Issue by ManasaGanesh** [Microsoft/Cognitive-SpeakerRecognition-Windows#2] opened 2016-07-21 05:03 UTC
Hi,

I am using Microsoft Cognitive Services speech API for my research . As I started using speech Identification API I see one problem with female voice identification . The system is falsely identifying speaker . It is accepting the different female speaker. 
Steps I followed
1)Enroll female speaker1
2)Try to identify speaker 2 against speaker1 
3)The system identified speaker 2 same as speaker 1
I don't see this problem with male speaker. I am not sure if I need to set any parameter for female speaker or is it  a flaw. Can anyone guide me on this.

**Comment by momohs** [comment] 2016-07-21 21:46
Hello @ManasaGanesh, there are no gender specific parameters for the speaker recognition. Can you please share with me the test data that you are using so that I can look further into this?

**Comment by ManasaGanesh** [comment] 2016-07-22 04:10
Hi  Team,
I am attaching the data set I used in testing .
I used 0.wav to enroll speaker  (Female 1) 
2,3 and 4.wav  for identifying (Female 2).

The system identified 2,3 and 4.wav voice as Female 1 which is incorrect.

Your help with this case is greatly appreciated.

Thanks,
Manasa



[New folder.zip](https://github.com/Microsoft/Cognitive-SpeakerRecognition-Windows/files/377435/New.folder.zip)

**Comment by momohs** [comment] 2016-07-24 16:15
Thanks for sharing this @ManasaGanesh! I will check this with the team and come back to you. 

The files sent are 0.wav and 2.wav only. It would be helpful if you can tell me what are the recording conditions for those files?

**Comment by ManasaGanesh** [comment] 2016-07-25 14:52
All I did was use the data set from http://festvox.org/cmu_arctic/ (US English slt (female) (0.95)<http://festvox.org/cmu_arctic/dbs_slt.html> US English clb (female) (0.95)<http://festvox.org/cmu_arctic/dbs_clb.html> )for the two female speakers.
I then merged the dataset  to have 60 second samples and set the sample rate and frequency as per the requirement of the system.
Since they sound similar the system falsely identifies the female speaker. I tried to add more samples, due to limitations in email size I am unable to attach more samples.
I am happy to provide more samples.
Thanks,
Manasa

**Comment by momohs** [comment] 2016-07-26 08:40
Thanks for your feedback @ManasaGanesh! Looking at the shared audio files, I would say that the gender of the speaker is not the cause of this error, but rather something else that we need to investigate e.g. the recording channel.

May I highlight that our system is trained using state of the art technology on balanced data that has speakers from both genders. You can read more about our system in this [blog post](https://blogs.technet.microsoft.com/machinelearning/2015/12/14/now-available-speaker-video-apis-from-microsoft-project-oxford/).

**Comment by ManasaGanesh** [comment] 2016-07-28 14:50
Thank you so much for your inputs. This tool is really helping me a lot in my research. I would test more female samples and see how it behaves.
As you told in your earlier email , may I know what is meant my balanced data. I can work on changing my dataset to respect that balanced form.
Your help is greatly appreciated.

Thanks,
Manasa

**Comment by momohs** [comment] 2016-07-28 15:34
I just meant that the training data we used contains both males and females. Please let me know if you have any more comments about the service.

**Comment by ManasaGanesh** [comment] 2016-07-28 15:42
I tested both male and female voice . System behaved well for male voice, 1 case failed out of 20 samples .
The probability that female voices failed was 9/10 cases. I am just concerned about this behavior.
According to your inputs this need more investigation. If that can be fixed this service will be best . I don’t have any other comments or issues with this tool.

Thanks,
Manasa

**Comment by momohs** [comment] 2016-07-28 15:58
All the female test cases were from the same corpus you shared earlier?

**Comment by ManasaGanesh** [comment] 2016-07-28 16:00
Yes also I tested non English female speakers from different dataset. I can share that if required.

Thanks,
Manasa

**Comment by momohs** [comment] 2016-07-28 16:38
Please share with me the english part. At this moment, the service only supports "en-us" locale as mentioned in the [documentation](https://dev.projectoxford.ai/docs/services/563309b6778daf02acc0a508/operations/5645c068e597ed22ec38f42e).

**Comment by ManasaGanesh** [comment] 2016-07-28 19:41
I can share the English dataset .
I have tested for same Arabic samples. It behaved well for male speakers. I was thinking that,  identification depends on voice print of speaker irrespective of language.

**Comment by momohs** [comment] 2016-08-01 09:35
True that the problem might seem to be language independent, however, the phonetics of each language  is different and that plays an important role in the performance of the system. At this moment, we only support english-US.

If I was in your place, I would try some more standard datasets e.g. TIMIT.

**Comment by ManasaGanesh** [comment] 2016-08-01 14:51
Hey ,
Thanks for your input. But I see that TIMIT is not free . Could you suggest me any open source which are of good standard .

Regards,
Manasa

**Comment by momohs** [comment] 2016-08-01 16:19
I'm not sure which datasets are for free and which are not. Please let me know if you have any further questions related to our service or SDK.

**Comment by momohs** [comment] 2016-08-04 14:49
I'll close this for now. Please feel free to re-open if you have any further questions.

**Closed by momohs** 2016-08-04 14:49 UTC
